-- 多媒体文件表
CREATE TABLE `multimedia` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `file_id` varchar(20) NOT NULL COMMENT '文件ID（雪花算法）',
  `user_id` varchar(20) NOT NULL COMMENT '上传用户ID，关联 users.user_id',
  `file_type` tinyint(1) unsigned NOT NULL COMMENT '文件类型：1-视频，2-图片，3-文本/文档，4-音频，5-其他',
  `file_name` varchar(255) NOT NULL COMMENT '原始文件名',
  `file_ext` varchar(20) NOT NULL DEFAULT '' COMMENT '文件扩展名（jpg/mp4/mp3/txt等）',
  `mime_type` varchar(100) NOT NULL DEFAULT '' COMMENT 'MIME类型',
  `file_size` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '文件大小（字节）',
  `storage_type` tinyint(1) unsigned NOT NULL DEFAULT '2' COMMENT '存储类型：1-本地，2-OSS，3-S3，4-COS',
  `original_uri` varchar(500) NOT NULL DEFAULT '' COMMENT '原始存储路径（OSS key）',
  `width` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '宽度（图片/视频）',
  `height` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '高度（图片/视频）',
  `duration` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '时长秒数（视频/音频）',
  `multi_imgs` text DEFAULT NULL COMMENT '多尺寸图片（JSON格式）',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态：0-上传中，1-成功，2-失败，3-已删除',
  `hash_md5` varchar(32) NOT NULL DEFAULT '' COMMENT '文件MD5（用于去重）',
  `hash_sha256` varchar(64) NOT NULL DEFAULT '' COMMENT '文件SHA256',
  `extra` text COMMENT '扩展字段（JSON格式）',
  `create_time` bigint(20) unsigned NOT NULL COMMENT '创建时间',
  `update_time` bigint(20) unsigned NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_id` (`file_id`),
  KEY `idx_user_type` (`user_id`,`file_type`),
  KEY `idx_status` (`status`),
  KEY `idx_hash_md5` (`hash_md5`),
  KEY `idx_user_md5` (`user_id`,`hash_md5`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='多媒体文件表';
