-- 帖子/内容表
CREATE TABLE `posts` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `post_id` varchar(36) NOT NULL COMMENT '帖子ID（UUID）',
  `user_id` varchar(36) NOT NULL COMMENT '用户ID，关联users.user_id',
  `post_type` tinyint(1) unsigned NOT NULL DEFAULT '3' COMMENT '帖子类型：1-视频，2-图片，3-文本',
  `title` varchar(200) DEFAULT NULL COMMENT '标题',
  `description` text COMMENT '描述',
  `content` text COMMENT '内容正文',
  `images` text DEFAULT NULL COMMENT '图片列表JSON(List[Image])',
  `video` json DEFAULT NULL COMMENT '视频信息：{id,height,width,duration,cover,main_url,back_urls}',
  `like_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '点赞数',
  `comment_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '评论数',
  `share_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '分享数',
  `view_count` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '浏览数',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '状态：0-草稿，1-正常，2-隐藏，3-删除',
  `source` tinyint(1) NOT NULL DEFAULT '0' COMMENT '来源：0-ugc, 1-pgc, 2-crawled',
  `source_platform` varchar(50) DEFAULT NULL COMMENT '来源平台：YouTube/Amazon/Reddit',
  `source_metadata` json DEFAULT NULL COMMENT '爬取元数据',
  `extra` text COMMENT '扩展字段',
  `create_time` bigint(20) unsigned NOT NULL COMMENT '创建时间',
  `update_time` bigint(20) unsigned NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_post_id` (`post_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_post_type` (`post_type`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`),
  KEY `idx_source` (`source`),
  KEY `idx_user_status_time` (`user_id`,`status`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='帖子/内容表';
